#ifndef MASSAGE_H
#define MASSAGE_H
//Authers: Chen Katz And Yotam Carmi

#define MAX_MASSAGE_TYPE 40
#define MAX_USER_NAME 20
#define SEND_STR_SIZE 120
#define MAX_ID_SIZE 16
//massages size drfinition:
//Client massages:
#define CLIENT_REQUEST 1
#define CLIENT_VERSUS 2
#define CLIENT_SETUP 3
#define CLIENT_PLAYER_MOVE 4
#define CLIENT_DISCONNECT 5
//end of client massages
//////////////////////////
//server massages:
#define SERVER_MAIN_MENU 6
#define SERVER_APPROVED 7
#define SERVER_DENIED 8
#define SERVER_INVITE 9
#define SERVER_SETUP_REQUEST 10
#define SERVER_PLAYER_MOVE_REQUEST 11
#define SERVER_GAME_RESULTS 12
#define SERVER_DRAW 13
#define SERVER_NO_OPPONENTS 14
#define SERVER_OPPONENT_QUIT 15
#define SERVER_WIN 16 
//end of server massages
//////////////////////////


//massages definition:
#define CLIENT_REQUEST_MSG "CLIENT_REQUEST:"
#define CLIENT_VERSUS_MSG "CLIENT_VERSUS\n"
#define CLIENT_SETUP_MSG "CLIENT_SETUP:"
#define CLIENT_PLAYER_MOVE_MSG "CLIENT_PLAYER_MOVE:"
#define CLIENT_DISCONNECT_MSG "CLIENT_DISCONNECT\n"
//end of client massages#
//////////////////////////
//server massages:
#define SERVER_MAIN_MENU_MSG "SERVER_MAIN_MENU\n"
#define SERVER_APPROVED_MSG "SERVER_APPROVED\n"
#define SERVER_DENIED_MSG "SERVER_DENIED:Server full"
#define SERVER_INVITE_MSG "SERVER_INVITE:"
#define SERVER_SETUP_REQUEST_MSG "SERVER_SETUP_REQUEST\n"
#define SERVER_PLAYER_MOVE_REQUEST_MSG "SERVER_PLAYER_MOVE_REQUEST\n"
#define SERVER_GAME_RESULTS_MSG "SERVER_GAME_RESULTS:"
#define SERVER_DRAW_MSG "SERVER_DRAW\n"
#define SERVER_NO_OPPONENTS_MSG "SERVER_NO_OPPONENTS\n"
#define SERVER_OPPONENT_QUIT_MSG "SERVER_OPPONENT_QUIT\n"
#define SERVER_WIN_MSG "SERVER_WIN:"

#define INVALID_MASSAGE_TYPE 17



#endif